// Code generated by protoc-gen-go. DO NOT EDIT.
// source: util.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("util.proto", fileDescriptor_170ba741606d8a4c)
}

var fileDescriptor_170ba741606d8a4c = []byte{
	// 48 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0xc9, 0xcc,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x49, 0x62, 0x03,
	0xf3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x57, 0xe0, 0x89, 0x1b, 0x00, 0x00, 0x00,
}
